// This file is automatically generated. Do not edit this file directly.
// Instead, make changes to the source files and regenerate this file.

export interface StorageProviderOption {
  value: string;
  label: string;
}